### ISSUE TITLE
Persist QuantumAlgorithm and QuantumInstance objects for inspection later

### ISSUE THREAD

**Issue by dongreenberg** [Qiskit/qiskit-chemistry#117]
### What is the expected enhancement?
It is convenient to run using the input dictionaries, but users often want to interact with the Aqua objects used in the Chemistry calculation later. We can save those objects to instance variables of the QiskitChemistry object, or return them from the run function.

**Comment by woodsp-ibm** [comment]
PR #121 enables access to these objects now
