### ISSUE TITLE
ExactEigensolver with backend, optimizer, variational form, or initial_state raises Error

### ISSUE THREAD

**Issue by mstypulk** [Qiskit/qiskit-chemistry#149]
### Informations

- **Qiskit Chemistry version**: 0.4.3 (master branch)
- **Python version**: 3.7.3
- **Operating system**: macOS

### What is the current behavior?
When I run a qiskit-chemistry experiment using a dictionary input, with ExactEigensolver as the algorithm and any of the following parameters added: backend, optimizer, initial_state, or variational_form, I receive the following error:
`AquaError: "Additional properties are not allowed ('variational_form', 'backend', 'optimizer', 'initial_state' were unexpected)"`

I know that it says AquaError, but I thought since the main action that was done was running the QuantumChemistry experiment, that this might have been the proper repo to post this issue. If I am wrong, I will happily move this issue to the Aqua repo.

### Steps to reproduce the problem
This was the block of code that I had run:
```
qiskit_chemistry_dict = {
    'driver': {'name': 'PYSCF'},
    'PYSCF': {'atom': 'H .0 .0 .0; Na .0 .0 1.1', 'basis': 'sto3g'},
    'operator': {'name': 'hamiltonian', 'qubit_mapping': 'parity',
                 'two_qubit_reduction': True, 'freeze_core': True, 'orbital_reduction': [-3, -2]},
    'algorithm': {'name': 'ExactEigensolver'},
    'optimizer': {'name': 'COBYLA', 'maxiter': 10000 },
    'variational_form': {'name': 'RYRZ'},
    'initial_state': {'name': 'HartreeFock'},
    'backend': {'name': 'statevector_simulator'}
}

solver = QiskitChemistry()
result = solver.run(qiskit_chemistry_dict)
```

This is the full stack trace:
```
AquaError                                 Traceback (most recent call last)
<ipython-input-31-49955aa676e3> in <module>
     33         qiskit_chemistry_dict['algorithm'] = algorithms[j]
     34         solver = QiskitChemistry()
---> 35         result = solver.run(qiskit_chemistry_dict)
     36         energies[j][i] = result['energy']
     37         hf_energies[i] = result['hf_energy']

/anaconda3/envs/qiskit_0.9_release/lib/python3.7/site-packages/qiskit_chemistry-0.4.3-py3.7.egg/qiskit/chemistry/qiskit_chemistry.py in run(self, params, output, backend)
    124             raise QiskitChemistryError("Missing input.")
    125 
--> 126         self.run_driver(params, backend)
    127         if self.hdf5_file:
    128             logger.info('No further process.')

/anaconda3/envs/qiskit_0.9_release/lib/python3.7/site-packages/qiskit_chemistry-0.4.3-py3.7.egg/qiskit/chemistry/qiskit_chemistry.py in run_driver(self, params, backend)
    176                 self._parser.set_section_property(JSONSchema.BACKEND, JSONSchema.PROVIDER, get_provider_from_backend(backend_name))
    177 
--> 178         self._parser.validate_merge_defaults()
    179         # logger.debug('ALgorithm Input Schema: {}'.format(json.dumps(p..get_sections(), sort_keys=True, indent=4)))
    180 

/anaconda3/envs/qiskit_0.9_release/lib/python3.7/site-packages/qiskit_chemistry-0.4.3-py3.7.egg/qiskit/chemistry/parser/_inputparser.py in validate_merge_defaults(self)
    223 
    224     def validate_merge_defaults(self):
--> 225         super().validate_merge_defaults()
    226         self._validate_operator_problem()
    227 

/anaconda3/envs/qiskit_0.9_release/lib/python3.7/site-packages/qiskit_aqua-0.4.2-py3.7.egg/qiskit/aqua/parser/base_parser.py in validate_merge_defaults(self)
    175     def validate_merge_defaults(self):
    176         self.merge_default_values()
--> 177         self._json_schema.validate(self.get_sections())
    178         self._validate_algorithm_problem()
    179 

/anaconda3/envs/qiskit_0.9_release/lib/python3.7/site-packages/qiskit_aqua-0.4.2-py3.7.egg/qiskit/aqua/parser/jsonschema.py in validate(self, sections_json)
    641         except jsonschema.exceptions.ValidationError as ve:
    642             logger.info('JSON Validation error: {}'.format(str(ve)))
--> 643             raise AquaError(ve.message)
    644 
    645     def validate_property(self, sections_json, section_name, property_name):

AquaError: "Additional properties are not allowed ('variational_form', 'backend', 'optimizer', 'initial_state' were unexpected)"
```

The error is thrown almost immediately.

### What is the expected behavior?

The experiment runs without issue.

**Comment by mstypulk** [comment]
After looking through everything a little deeper, I believe this may be more of a bug within Aqua. I will try moving the issue to the Aqua repo.

**Comment by woodsp-ibm** [comment]
An `optimizer` and `variational_form` are only needed when using VQE, a quantum algorithm, that also needs a `backend` i.e. a quantum device/simulator upon which to run. `initial_state` is used by the variational form ansatz.

None of those entities are needed if you choose to use the ExactEigensolver algorithm to solve the problem. It is a classical algorithm which finds eigenvalues bu converting the Operator to matrix form.

The experiment is validated by schema which detects the incorrect presence of those other components and gives the error you see. This is expected behavior. Remove them and it will work

**Comment by mstypulk** [comment]
Ahh ok, I see. I understand the error now. I was confused because when I had run this experiment on the stable version of qiskit, it ran without this error. Only running it on the master branch version of the qiskit repos gave me this error. Thank you for your response and explanation though.

**Comment by woodsp-ibm** [comment]
I think in earlier versions we may have incorrectly ignored dependent components that were not needed. I do not recall exactly when this changed but it now validates complete correctness and will not allow component parts to be included that are not required in the configuration for the experiment

**Comment by mstypulk** [comment]
That all makes sense, and I'll keep it in mind if I run into this error in the future. Thank you for your help and explanation!
