### ISSUE TITLE
10 undefined names

### ISSUE THREAD

**Issue by cclauss** [Qiskit/qiskit-chemistry#25]
### Informations

- **Qiskit Aqua Chemistry version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
[flake8](http://flake8.pycqa.org) testing of https://github.com/Qiskit/aqua-chemistry on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:235:22: F821 undefined name 'kwargs'
    print ("error",**kwargs)
                     ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:515:12: F821 undefined name 'self'
    ntot = self.lenarr
           ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:516:21: F821 undefined name 'self'
    lenbx = lenbuf//self.nelem
                    ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:517:9: F821 undefined name 'self'
    y = self.array.reshape((self.nelem,ntot),order='F')
        ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:517:29: F821 undefined name 'self'
    y = self.array.reshape((self.nelem,ntot),order='F')
                            ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:519:5: F821 undefined name 'wr_labl'
    wr_labl(iu,self.name,1,nr,nnz,lenbx,ntot,1,1,1,1,0)
    ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:519:16: F821 undefined name 'self'
    wr_labl(iu,self.name,1,nr,nnz,lenbx,ntot,1,1,1,1,0)
               ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:519:28: F821 undefined name 'nr'
    wr_labl(iu,self.name,1,nr,nnz,lenbx,ntot,1,1,1,1,0)
                           ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCOpMat.py:520:5: F821 undefined name 'wr_rind'
    wr_rind(iu,nnz,lenbx,y)
    ^
./qiskit_aqua_chemistry/drivers/gaussiand/gauopen/QCMatEl.py:355:5: F821 undefined name 'unlink'
    unlink (matfo)
    ^
10    F821 undefined name 'unlink'
10
```

### Steps to reproduce the problem
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__

### What is the expected behavior?
No errors

### Suggested solutions
#24 to fix the __unlink (matfo)__ issue.

The _self_ issues are probably a result of moving code that is in Class methods into normal functions.

**Comment by woodsp-ibm** [comment]
The code referred to here is 3rd party sourced/maintained code that has been provided here for convenience. The use of this code by Aqua Chemistry is limited to simply reading a 3rd party created file and the specific code containing these issues is not used. I have however passed this information on to the 3rd party that hopefully they can be rectified even though they do not affect Aqua Chemistry's use of this code.
